name: brain-pong-inputs
channels:
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.12.0
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - hdf5=1.14.5
  - libcurl=8.15.0
  - libcxx=20.1.8
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libssh2=1.11.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openssl=3.0.17
  - packaging=25.0
  - pip=25.2
  - py-cpuinfo=9.0.0
  - pytables=3.10.1
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.7
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cryptography==46.0.1
      - cycler==0.12.1
      - decorator==5.2.1
      - dukpy==0.2.3
      - elementpath==5.0.4
      - esprima==4.0.1
      - et-xmlfile==2.0.0
      - ffpyplayer==4.5.3
      - fonttools==4.60.0
      - freetype-py==2.5.1
      - future==1.0.0
      - gevent==25.9.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - idna==3.10
      - ifaddr==0.2.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - javascripthon==0.13
      - jedi==0.19.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - meshpy==2025.1.1
      - moviepy==2.2.1
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.2
      - parso==0.8.5
      - pillow==11.3.0
      - proglog==0.1.12
      - psutil==7.1.0
      - psychopy==2025.1.1
      - psychtoolbox==3.0.19.14
      - pyarrow==21.0.0
      - pycparser==2.23
      - pyglet==1.5.27
      - pyobjc==7.3
      - pyobjc-core==7.3
      - pyobjc-framework-accessibility==7.3
      - pyobjc-framework-accounts==7.3
      - pyobjc-framework-addressbook==7.3
      - pyobjc-framework-adservices==7.3
      - pyobjc-framework-adsupport==7.3
      - pyobjc-framework-applescriptkit==7.3
      - pyobjc-framework-applescriptobjc==7.3
      - pyobjc-framework-applicationservices==7.3
      - pyobjc-framework-apptrackingtransparency==7.3
      - pyobjc-framework-authenticationservices==7.3
      - pyobjc-framework-automaticassessmentconfiguration==7.3
      - pyobjc-framework-automator==7.3
      - pyobjc-framework-avfoundation==7.3
      - pyobjc-framework-avkit==7.3
      - pyobjc-framework-businesschat==7.3
      - pyobjc-framework-calendarstore==7.3
      - pyobjc-framework-callkit==7.3
      - pyobjc-framework-cfnetwork==7.3
      - pyobjc-framework-classkit==7.3
      - pyobjc-framework-cloudkit==7.3
      - pyobjc-framework-cocoa==7.3
      - pyobjc-framework-collaboration==7.3
      - pyobjc-framework-colorsync==7.3
      - pyobjc-framework-contacts==7.3
      - pyobjc-framework-contactsui==7.3
      - pyobjc-framework-coreaudio==7.3
      - pyobjc-framework-coreaudiokit==7.3
      - pyobjc-framework-corebluetooth==7.3
      - pyobjc-framework-coredata==7.3
      - pyobjc-framework-corehaptics==7.3
      - pyobjc-framework-corelocation==7.3
      - pyobjc-framework-coremedia==7.3
      - pyobjc-framework-coremediaio==7.3
      - pyobjc-framework-coremidi==7.3
      - pyobjc-framework-coreml==7.3
      - pyobjc-framework-coremotion==7.3
      - pyobjc-framework-coreservices==7.3
      - pyobjc-framework-corespotlight==7.3
      - pyobjc-framework-coretext==7.3
      - pyobjc-framework-corewlan==7.3
      - pyobjc-framework-cryptotokenkit==7.3
      - pyobjc-framework-devicecheck==7.3
      - pyobjc-framework-dictionaryservices==7.3
      - pyobjc-framework-discrecording==7.3
      - pyobjc-framework-discrecordingui==7.3
      - pyobjc-framework-diskarbitration==7.3
      - pyobjc-framework-dvdplayback==7.3
      - pyobjc-framework-eventkit==7.3
      - pyobjc-framework-exceptionhandling==7.3
      - pyobjc-framework-executionpolicy==7.3
      - pyobjc-framework-externalaccessory==7.3
      - pyobjc-framework-fileprovider==7.3
      - pyobjc-framework-fileproviderui==7.3
      - pyobjc-framework-findersync==7.3
      - pyobjc-framework-fsevents==7.3
      - pyobjc-framework-gamecenter==7.3
      - pyobjc-framework-gamecontroller==7.3
      - pyobjc-framework-gamekit==7.3
      - pyobjc-framework-gameplaykit==7.3
      - pyobjc-framework-imagecapturecore==7.3
      - pyobjc-framework-imserviceplugin==7.3
      - pyobjc-framework-inputmethodkit==7.3
      - pyobjc-framework-installerplugins==7.3
      - pyobjc-framework-instantmessage==7.3
      - pyobjc-framework-intents==7.3
      - pyobjc-framework-iosurface==7.3
      - pyobjc-framework-ituneslibrary==7.3
      - pyobjc-framework-kernelmanagement==7.3
      - pyobjc-framework-latentsemanticmapping==7.3
      - pyobjc-framework-launchservices==7.3
      - pyobjc-framework-libdispatch==7.3
      - pyobjc-framework-linkpresentation==7.3
      - pyobjc-framework-localauthentication==7.3
      - pyobjc-framework-mapkit==7.3
      - pyobjc-framework-mediaaccessibility==7.3
      - pyobjc-framework-medialibrary==7.3
      - pyobjc-framework-mediaplayer==7.3
      - pyobjc-framework-mediatoolbox==7.3
      - pyobjc-framework-metal==7.3
      - pyobjc-framework-metalkit==7.3
      - pyobjc-framework-metalperformanceshaders==7.3
      - pyobjc-framework-metalperformanceshadersgraph==7.3
      - pyobjc-framework-mlcompute==7.3
      - pyobjc-framework-modelio==7.3
      - pyobjc-framework-multipeerconnectivity==7.3
      - pyobjc-framework-naturallanguage==7.3
      - pyobjc-framework-netfs==7.3
      - pyobjc-framework-network==7.3
      - pyobjc-framework-networkextension==7.3
      - pyobjc-framework-notificationcenter==7.3
      - pyobjc-framework-opendirectory==7.3
      - pyobjc-framework-osakit==7.3
      - pyobjc-framework-oslog==7.3
      - pyobjc-framework-passkit==7.3
      - pyobjc-framework-pencilkit==7.3
      - pyobjc-framework-photos==7.3
      - pyobjc-framework-photosui==7.3
      - pyobjc-framework-preferencepanes==7.3
      - pyobjc-framework-pushkit==7.3
      - pyobjc-framework-quartz==7.3
      - pyobjc-framework-quicklookthumbnailing==7.3
      - pyobjc-framework-replaykit==7.3
      - pyobjc-framework-safariservices==7.3
      - pyobjc-framework-scenekit==7.3
      - pyobjc-framework-screensaver==7.3
      - pyobjc-framework-screentime==7.3
      - pyobjc-framework-scriptingbridge==7.3
      - pyobjc-framework-searchkit==7.3
      - pyobjc-framework-security==7.3
      - pyobjc-framework-securityfoundation==7.3
      - pyobjc-framework-securityinterface==7.3
      - pyobjc-framework-servicemanagement==7.3
      - pyobjc-framework-social==7.3
      - pyobjc-framework-soundanalysis==7.3
      - pyobjc-framework-speech==7.3
      - pyobjc-framework-spritekit==7.3
      - pyobjc-framework-storekit==7.3
      - pyobjc-framework-syncservices==7.3
      - pyobjc-framework-systemconfiguration==7.3
      - pyobjc-framework-systemextensions==7.3
      - pyobjc-framework-uniformtypeidentifiers==7.3
      - pyobjc-framework-usernotifications==7.3
      - pyobjc-framework-usernotificationsui==7.3
      - pyobjc-framework-videosubscriberaccount==7.3
      - pyobjc-framework-videotoolbox==7.3
      - pyobjc-framework-virtualization==7.3
      - pyobjc-framework-vision==7.3
      - pyobjc-framework-webkit==7.3
      - pyparsing==3.2.5
      - pyqt6==6.9.1
      - pyqt6-qt6==6.9.2
      - pyqt6-sip==13.10.2
      - pyserial==3.5
      - python-bidi==0.6.6
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-gitlab==6.3.0
      - python-vlc==3.0.21203
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - questplus==2023.1
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - ruff==0.13.2
      - scipy==1.15.3
      - setuptools==70.3.0
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - tqdm==4.67.1
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - wxpython==4.2.3
      - xarray==2025.6.1
      - xmlschema==4.1.0
      - zeroconf==0.147.2
      - zope-event==5.1
      - zope-interface==8.0
