# Level configurations for experiment
#
# Note that paddle heights are in normalized units; they are normalized to the 
# window height and therefore maintain the same relative size invariant of 
# window size
# ----------------------------------------------------------------------------

0:
  paddle_size: 0.5
  point_increment: 1
1:
  paddle_size: 0.4
  point_increment: 2
2:
  paddle_size: 0.3
  point_increment: 3
3:
  paddle_size: 0.2
  point_increment: 4
4:
  paddle_size: 0.1
  point_increment: 5
